-- Packages installed manually on the system (auto-synced by dcli).
-- amd-ucode, nvidia-open-dkms, libva-nvidia-driver, linux/linux-firmware are
-- handled by modules/hardware.lua and intentionally absent here.

return {
    description = "Packages installed manually on the system (auto-synced by dcli)",
    packages = {
        "ark",
        "bluez",
        "bluez-utils",
        "btrfs-progs",
        "cups",
        "cups-pk-helper",
        "dcli-arch-git",
        "dhcpcd",
        "dkms",
        "dolphin",
        "efibootmgr",
        "git",
        "gst-plugin-pipewire",
        "htop",
        "iwd",
        "kate",
        "konsole",
        "libpulse",
        "linux",
        "linux-headers",
        "nano",
        "openssh",
        "pipewire",
        "pipewire-alsa",
        "pipewire-jack",
        "pipewire-pulse",
        "plasma-meta",
        "plasma-workspace",
        "sddm",
        "smartmontools",
        "sudo",
        "system-config-printer",
        "vim",
        "wget",
        "wireless_tools",
        "wireplumber",
        "xdg-utils",
        "xorg-server",
        "xorg-xinit",
        "yay",
        "yay-debug",
        "zram-generator",
    },
}
