return {
    description = "Hyprland dynamic tiling Wayland compositor with waybar + wofi",
    conflicts = {
        "desktop-environments/niri",
        "desktop-environments/kde-plasma",
    },
    dotfiles_sync = true,
    packages = {
        "hyprland",
        "hyprlock",
        "hypridle",
        "hyprpaper",
        "hyprshot",
        "waybar",
        "wofi",
        "dunst",
        "swaync",
        "grim",
        "slurp",
        "xdg-desktop-portal-hyprland",
        "polkit-kde-agent",
        "qt5-wayland",
        "qt6-wayland",
        "wl-clipboard",
        "cliphist",
        "pavucontrol",
        "blueman",
        "network-manager-applet",
        "nwg-look",
        "brightnessctl",
    },
}
